data = {
    "cmnd":
        {
            "name": "Tran Ngoc Son",
            "id_card": "001097001273",
            "dob": "21-03-1997",
            "sex": "Nam",
            "nationality": "Viet Nam",
            "poo": "Duc giang long bien ha noi",
            "por": "Duc giang long bien ha noi",
            "doe": "25-12-2024",
            "pi": "Not ruoi phai qua nhieu",
            "dop": "21-03-2021",
            "poi": "CCS HN"
        },
    "stk": {
        "CIF": "1245",
        "name": "Tran Ngoc Son",
        "dob": "21-03-1997",
        "id_def": "001097002162",
        "datetime_id": "21-03-2021",
        "addr_id": "CCS HN",
        "seri_number": "A1231224",
        "product_number": "Tien mat",
        "TKFD": "503-20215-28124",
        "period": "6",
        "date_ex": "25-12-2025",
        "price": "30,000,000"
    },
    "hochieu": {
        "name": "Tran Ngoc Son",
        "id": "2093181237",
        "dob": "21-03-1997",
        "sex": "nam",
        "nationality": "Viet Nam",
        "pob": "Ha Noi",
        "doe": "25-12-2040",
        "dop": "21-03-2021",
        "poi": "Ha Noi city",
        "type": "A",
        "code": "A-12321472"
    },
    "dkkd": {
        "name_VN": "Nhun Nguyen Company",
        "name_other": "Nhun Nguyen C",
        "name_code": "NNC",
        "addr": "Vincom Ba trieu",
        "phone_number": "0978321212",
        "email": "transon.hvnh@gmail.com",
        "website": "nhunnguyen.com.vn",
        "equity": "500,000,000",
        "incharge": "Tran Ngoc Son",
        "company_code": "A12321312",
        "dof": "21-03-2019",
        "number_change": "2",
        "change_datetime": "13-15-2021",
        "sex": "Nam",
        "title": "CEO",
        "dob": "21-03-1997",
        "region": "Viet Nam",
        "id_def": "cmnd",
        "doi": "21-03-2021",
        "incharge_addr": "Duc giang long bien ha noi",
        "incharge_addr_now": "Duc Giang long bien ha noi"
    },
    "sohong": {
        "name_mr": "Tran Ngoc Son",
        "dob_mr": "21-03-1997",
        "id_card_mr": "001097007764",
        "addr_mr": "Duc giang long bien ha noi",
        "name_mrs": "Nguyen thi hong nhung",
        "dob_mrs": "09-03-1995",
        "id_card_mrs": "00129212312737",
        "addr_mrs": "Bo De long bien ha noi",
        "id_def": "213213213",
        "id_place": "21",
        "id_map": "2",
        "addr_def": "Ha Tay Viet Nam",
        "vacant": "1000",
        "type": "ca nhan",
        "objective": "cho thue",
        "datetime": "10",
        "source": "mua lai",
        "note": "thuong la text",
        "house_addr": "Duc giang long bien ha noi",
        "vacant_house_building": "500",
        "vacant_house_size": "300",
        "type_house": "vuong",
        "level_house": "5",
        "building_done": "2021",
        "datetime_house": "10",
        "place_def": "Ha Noi",
        "datetime_place": "21-12-2010",
        "signature": "Ha Noi",
        "code_def": "293823"
    }

}
